services:
  - type: web
    name: survival-island-battle
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: survival-island-battle
          property: port
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    autoDeploy: false
    healthCheckPath: /health